dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user prueba password 'prueba'"
  - psql -U postgres -c "create database test_prueba owner prueba"
  - psql -U postgres -c "ALTER USER prueba CREATEDB"
  - psql -U postgres -c "ALTER ROLE prueba Superuser"
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  
script:
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test
  - coverage xml

deploy:
  provider: heroku
  app: futbolstats-prueba
  strategy: git
  apikey: 330e6c22-e5b9-442c-8aab-da7656da65a1
  on:
    branch: master
