# Generated by Django 3.1.4 on 2021-10-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('logo', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
