# Generated by Django 3.1.4 on 2021-11-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticasportero',
            old_name='penaltiesEncagados',
            new_name='penaltiesEncajados',
        ),
    ]
