# Generated by Django 3.1.4 on 2021-04-09 14:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('escudo', models.CharField(max_length=200)),
                ('partidosJugados', models.IntegerField()),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('golesFavor', models.IntegerField()),
                ('golesContra', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasCreacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasesGol', models.IntegerField()),
                ('pasesMuertosGol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasDefensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas', models.IntegerField()),
                ('entradasAtaque', models.IntegerField()),
                ('entradasMedio', models.IntegerField()),
                ('entradasDefensa', models.IntegerField()),
                ('entradasGanadas', models.IntegerField()),
                ('presion', models.IntegerField()),
                ('presionAtaque', models.IntegerField()),
                ('presionMedio', models.IntegerField()),
                ('presionGanada', models.IntegerField()),
                ('presionDefensa', models.IntegerField()),
                ('intentoRegate', models.IntegerField()),
                ('regateParado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasDiversas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balonesAereosGanados', models.IntegerField()),
                ('balonesAereosPerdidos', models.IntegerField()),
                ('balonesSueltosRecuperados', models.IntegerField()),
                ('amarillas', models.IntegerField()),
                ('dobleAmarillas', models.IntegerField()),
                ('rojas', models.IntegerField()),
                ('faltasRecibidas', models.IntegerField()),
                ('faltasCometidas', models.IntegerField()),
                ('fueraJuego', models.IntegerField()),
                ('penaltiesConcedidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidosJugados', models.IntegerField()),
                ('titular', models.IntegerField()),
                ('partidosCompletos', models.IntegerField()),
                ('entraSuplente', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('minutosJugados', models.IntegerField()),
                ('asistencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasPases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanciaPases', models.IntegerField()),
                ('pasesCortos', models.IntegerField()),
                ('pasesCortosEfectivos', models.IntegerField()),
                ('pasesMedios', models.IntegerField()),
                ('pasesMediosEfectivos', models.IntegerField()),
                ('pasesLargos', models.IntegerField()),
                ('pasesLargosEfectivos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasPortero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golesRecibidos', models.IntegerField()),
                ('tirosRecibidos', models.IntegerField()),
                ('paradasRecibidos', models.IntegerField()),
                ('cleanSheet', models.IntegerField()),
                ('penaltiesEncagados', models.IntegerField()),
                ('penaltiesParados', models.IntegerField()),
                ('penaltiesFalladosContrario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasRegates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balonTocadoAreaPenaltyPropia', models.IntegerField()),
                ('balonTocadoDefensa', models.IntegerField()),
                ('balonTocadoMedio', models.IntegerField()),
                ('balonTocadoAtaque', models.IntegerField()),
                ('balonTocadoAreaPenaltyContr', models.IntegerField()),
                ('regates', models.IntegerField()),
                ('regatesCompletados', models.IntegerField()),
                ('controles', models.IntegerField()),
                ('distanciaPosesion', models.IntegerField()),
                ('controlesFallidos', models.IntegerField()),
                ('pasesObjetivo', models.IntegerField()),
                ('pasesRecibidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasTipoPases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conPresion', models.IntegerField()),
                ('centros', models.IntegerField()),
                ('pasesPieDerecho', models.IntegerField()),
                ('pasesPieIzquierdo', models.IntegerField()),
                ('pasesCabeza', models.IntegerField()),
                ('cornersLanzados', models.IntegerField()),
                ('pasesFueraJuego', models.IntegerField()),
                ('pasesFueraCampo', models.IntegerField()),
                ('paseSuelo', models.IntegerField()),
                ('paseBajo', models.IntegerField()),
                ('paseAlto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasTiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiros', models.IntegerField()),
                ('tirosPorteria', models.IntegerField()),
                ('distanciaTiros', models.FloatField()),
                ('tirosFalta', models.IntegerField()),
                ('penalties', models.IntegerField()),
                ('penaltiesMarcados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('logo', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombreCompleto', models.CharField(max_length=80)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('fechaDeNacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('pie', models.CharField(choices=[('Izquierda', 'Zurdo'), ('Derecha', 'Diestro'), ('Ambos', 'Ambidiestro')], max_length=10)),
                ('posicion', models.CharField(choices=[('PO', 'Portero'), ('DF', 'Defensa'), ('CC', 'CentroCampista'), ('DL', 'Delantero')], max_length=2)),
                ('demarcaciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=None)),
                ('foto', models.CharField(max_length=150)),
                ('equipoActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=30)),
                ('equipo', models.CharField(max_length=80)),
                ('estadisticasDefensa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasdefensa')),
                ('estadisticasDiversas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasdiversas')),
                ('estadisticasGenerales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasgenerales')),
                ('estadisticasPases', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticaspases')),
                ('estadisticasPortero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasportero')),
                ('estadisticasTipoPases', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticastipopases')),
                ('estadisticasTiros', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticastiros')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.liga'),
        ),
    ]
