# Generated by Django 3.1.4 on 2021-04-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolStats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticasjugador',
            name='EstadisticasCreacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticascreacion'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='equipo',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasDefensa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasdefensa'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasDiversas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasdiversas'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasGenerales',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasgenerales'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasPases',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticaspases'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasPortero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasportero'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasTipoPases',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticastipopases'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='estadisticasTiros',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticastiros'),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='temporada',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='altura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fechaDeNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='peso',
            field=models.FloatField(null=True),
        ),
    ]
