# Generated by Django 3.1.4 on 2021-04-09 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolStats', '0002_auto_20210409_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='demarcaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), null=True, size=None),
        ),
    ]
