# Generated by Django 3.1.4 on 2021-04-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolStats', '0003_auto_20210409_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticasjugador',
            old_name='EstadisticasCreacion',
            new_name='estadisticasCreacion',
        ),
        migrations.AddField(
            model_name='estadisticasjugador',
            name='estadisticasRegates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FutbolStats.estadisticasregates'),
        ),
    ]
