# Generated by Django 3.1.4 on 2021-10-10 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolStats', '0004_auto_20210410_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='demarcaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), null=True, size=None),
        ),
    ]
