# Generated by Django 3.1.4 on 2021-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolStats', '0005_auto_20211010_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='derrotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='empates',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='golesContra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='golesFavor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='partidosJugados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='victorias',
            field=models.IntegerField(null=True),
        ),
    ]
